# Generated by Django 5.1.1 on 2024-10-26 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=40)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=50000.0)),
            ],
        ),
    ]
