# Generated by Django 5.1.1 on 2024-10-26 20:33

import category.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_productcategory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=category.models.category_image_path),
        ),
    ]
