# Generated by Django 5.0 on 2023-12-27 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carts', '0001_initial'),
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='item',
            field=models.ManyToManyField(blank=True, related_name='add_item', to='items.selected'),
        ),
    ]
