# Generated by Django 5.1.1 on 2024-10-24 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customusers',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='customusers',
            name='subscribe',
        ),
        migrations.RemoveField(
            model_name='customusers',
            name='vendor',
        ),
    ]
