# Generated by Django 5.1.1 on 2024-11-03 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_customusers_phone_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customusers',
            options={'verbose_name': 'Admin', 'verbose_name_plural': 'Administrative Users'},
        ),
    ]
