# Generated by Django 5.0 on 2023-12-27 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='feature',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='promo',
            field=models.CharField(choices=[('banner', 'Banner'), ('trending', 'Trending')], default='banner', max_length=20),
            preserve_default=False,
        ),
    ]
