# Generated by Django 5.0 on 2023-12-27 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_category_feature_item_promo'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='items.category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='promo',
            field=models.CharField(choices=[('basic', 'Basic'), ('banner', 'Banner'), ('trending', 'Trending'), ('popular', 'Popular')], max_length=20),
        ),
    ]
