# Generated by Django 5.0 on 2023-12-27 22:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_item_category_alter_item_promo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_item', to=settings.AUTH_USER_MODEL)),
                ('item', models.ManyToManyField(related_name='wishlist_item', to='items.itemwiththumbs')),
            ],
        ),
    ]
