# Generated by Django 5.0 on 2023-12-27 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_wishlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='item',
            new_name='items',
        ),
        migrations.AddField(
            model_name='upload',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='upload_item', to='items.item'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itemwiththumbs',
            name='thumbs',
            field=models.ManyToManyField(blank=True, related_name='item_images', to='items.upload'),
        ),
    ]
