# Generated by Django 4.0.4 on 2022-05-14 10:44

from django.db import migrations, models
import ness.models


class Migration(migrations.Migration):

    dependencies = [
        ('ness', '0002_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to=ness.models.upload_path),
        ),
    ]
