# Generated by Django 4.0.4 on 2022-05-18 17:57

from django.db import migrations, models
import ness.models


class Migration(migrations.Migration):

    dependencies = [
        ('ness', '0003_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, upload_to=ness.models.cat_path),
        ),
    ]
