# Generated by Django 4.0.4 on 2022-05-19 10:52

from django.db import migrations, models
import ness.models


class Migration(migrations.Migration):

    dependencies = [
        ('ness', '0004_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, upload_to=ness.models.cat_path, validators=[ness.models.validate_cat]),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to=ness.models.upload_path, validators=[ness.models.validate_product]),
        ),
    ]
