# Generated by Django 5.1.1 on 2024-11-03 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0002_product_condition'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=50)),
                ('created_for', models.CharField(max_length=50)),
                ('for_email', models.EmailField(max_length=254)),
                ('by_email', models.EmailField(max_length=254)),
                ('authorization_code', models.CharField(blank=True, max_length=16, null=True)),
                ('reference_code', models.CharField(blank=True, max_length=12, null=True)),
                ('status', models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('delivered', 'Delivered'), ('completed', 'Completed')], default='UNPAID', max_length=9)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('cart', models.ManyToManyField(blank=True, to='product.product')),
            ],
        ),
    ]
