# Generated by Django 5.1.1 on 2024-11-03 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='order',
            name='mode',
            field=models.CharField(choices=[('ship', 'ship'), ('pickup', 'pickup')], default='ship', max_length=10),
            preserve_default=False,
        ),
    ]
