# Generated by Django 5.1.1 on 2024-11-04 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=16, null=True)),
                ('title', models.CharField(blank=True, max_length=40, null=True)),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('hero', models.ImageField(blank=True, null=True, upload_to='')),
                ('description', models.TextField(default='')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=14, null=True)),
                ('created_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'App Data',
                'verbose_name_plural': 'Application Information',
            },
        ),
    ]
