# Generated by Django 5.1.1 on 2024-11-06 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_config', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appmodel',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appmodel',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appmodel',
            name='whatsapp',
            field=models.URLField(blank=True, null=True),
        ),
    ]
