# Generated by Django 5.1.1 on 2024-10-26 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thumbs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='Product',
            new_name='product',
        ),
    ]
