# Generated by Django 5.1.1 on 2024-11-01 19:14

import thumbs.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thumbs', '0002_rename_product_productimage_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='img',
            field=thumbs.models.ImageField(upload_to=thumbs.models.product_image_path, verbose_name='Upload Image'),
        ),
    ]
